### ISSUE TITLE
Error Loading Extension

### ISSUE THREAD

**Issue by BryceStevenWilley** [jay-khatri/Hack-Rice#1]
```
Failed to load extension from: ~/temp/GitStub/Hack-Rice
Could not load javascript 'd3.min.js' for content script.
```

Trying on  Chrome 53.0.2785.143 on Mac El Captian.

Love the idea, definitely want to get it working.

**Comment by SnoopJ** [comment]
Thanks for the report, should be fixed now.  ♥
